apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  sources:
    # Source 1 : le chart kube-prometheus-stack (Prometheus + Grafana + Alertmanager)
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 65.5.1
      helm:
        valueFiles:
          - $values/tp6-app/manifests/infrastructure/monitoring/values-prometheus.yaml
    # Source 2 : le dépôt GitOps qui contient nos values (nommé "values")
    - repoURL: https://github.com/TysonNemeghaire1/dev-cloud.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true   # les CRD volumineux de kube-prometheus-stack
