apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/TysonNemeghaire1/dev-cloud.git
    targetRevision: main
    path: tp6-app/manifests/infrastructure/kafka
  destination:
    server: https://kubernetes.default.svc
    namespace: fraudguard
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
